var hierarchy =
[
    [ "Keskus.DAL.Administrator", "class_keskus_1_1_d_a_l_1_1_administrator.html", null ],
    [ "Keskus.BLL.Administrator.AdministratorBO", "class_keskus_1_1_b_l_l_1_1_administrator_1_1_administrator_b_o.html", null ],
    [ "Keskus.BLL.Administrator.AdministratorService", "class_keskus_1_1_b_l_l_1_1_administrator_1_1_administrator_service.html", null ],
    [ "Application", null, [
      [ "Keskus.App", "class_keskus_1_1_app.html", null ],
      [ "Keskus.App", "class_keskus_1_1_app.html", null ],
      [ "Keskus.App", "class_keskus_1_1_app.html", null ]
    ] ],
    [ "Keskus.DAL.Booking", "class_keskus_1_1_d_a_l_1_1_booking.html", null ],
    [ "Keskus.BLL.Booking.BookingBO", "class_keskus_1_1_b_l_l_1_1_booking_1_1_booking_b_o.html", null ],
    [ "Keskus.BLL.Booking.BookingService", "class_keskus_1_1_b_l_l_1_1_booking_1_1_booking_service.html", null ],
    [ "Keskus.DAL.Contact", "class_keskus_1_1_d_a_l_1_1_contact.html", null ],
    [ "Keskus.BLL.Contact.ContactBO", "class_keskus_1_1_b_l_l_1_1_contact_1_1_contact_b_o.html", null ],
    [ "Keskus.BLL.Contact.ContactService", "class_keskus_1_1_b_l_l_1_1_contact_1_1_contact_service.html", null ],
    [ "Keskus.DAL.ContactType", "class_keskus_1_1_d_a_l_1_1_contact_type.html", null ],
    [ "Keskus.BLL.ContactType.ContactTypeBO", "class_keskus_1_1_b_l_l_1_1_contact_type_1_1_contact_type_b_o.html", null ],
    [ "Keskus.BLL.ContactType.ContactTypeService", "class_keskus_1_1_b_l_l_1_1_contact_type_1_1_contact_type_service.html", null ],
    [ "Keskus.DAL.Customer", "class_keskus_1_1_d_a_l_1_1_customer.html", null ],
    [ "Keskus.BLL.Customer.CustomerBO", "class_keskus_1_1_b_l_l_1_1_customer_1_1_customer_b_o.html", null ],
    [ "Keskus.BLL.Customer.CustomerService", "class_keskus_1_1_b_l_l_1_1_customer_1_1_customer_service.html", null ],
    [ "Keskus.BLL.Customer.Tests.CustomerServiceTests", "class_keskus_1_1_b_l_l_1_1_customer_1_1_tests_1_1_customer_service_tests.html", null ],
    [ "DbContext", null, [
      [ "Keskus.DAL.Keskus_baasEntities", "class_keskus_1_1_d_a_l_1_1_keskus__baas_entities.html", null ]
    ] ],
    [ "Keskus.BLL.Report.ExportBO", "class_keskus_1_1_b_l_l_1_1_report_1_1_export_b_o.html", null ],
    [ "Keskus.BLL.Filter", "class_keskus_1_1_b_l_l_1_1_filter.html", null ],
    [ "IComponentConnector", null, [
      [ "Keskus.AddCustomerV", "class_keskus_1_1_add_customer_v.html", null ],
      [ "Keskus.BookingDetails", "class_keskus_1_1_booking_details.html", null ],
      [ "Keskus.BookingDetailsV", "class_keskus_1_1_booking_details_v.html", null ],
      [ "Keskus.BookingsConfirmedV", "class_keskus_1_1_bookings_confirmed_v.html", null ],
      [ "Keskus.BookingsConfirmedV", "class_keskus_1_1_bookings_confirmed_v.html", null ],
      [ "Keskus.BookingsUnconfirmedV", "class_keskus_1_1_bookings_unconfirmed_v.html", null ],
      [ "Keskus.BookingsUnconfirmedV", "class_keskus_1_1_bookings_unconfirmed_v.html", null ],
      [ "Keskus.BookingUpdateV", "class_keskus_1_1_booking_update_v.html", null ],
      [ "Keskus.BookingUpdateV", "class_keskus_1_1_booking_update_v.html", null ],
      [ "Keskus.CalendarV", "class_keskus_1_1_calendar_v.html", null ],
      [ "Keskus.CalenderV", "class_keskus_1_1_calender_v.html", null ],
      [ "Keskus.ConfBookingsV", "class_keskus_1_1_conf_bookings_v.html", null ],
      [ "Keskus.CustomerAddV", "class_keskus_1_1_customer_add_v.html", null ],
      [ "Keskus.CustomerAddV", "class_keskus_1_1_customer_add_v.html", null ],
      [ "Keskus.CustomersV", "class_keskus_1_1_customers_v.html", null ],
      [ "Keskus.CustomersV", "class_keskus_1_1_customers_v.html", null ],
      [ "Keskus.CustomerUpdateV", "class_keskus_1_1_customer_update_v.html", null ],
      [ "Keskus.CustomerUpdateV", "class_keskus_1_1_customer_update_v.html", null ],
      [ "Keskus.LoginV", "class_keskus_1_1_login_v.html", null ],
      [ "Keskus.LoginV", "class_keskus_1_1_login_v.html", null ],
      [ "Keskus.MainMenuV", "class_keskus_1_1_main_menu_v.html", null ],
      [ "Keskus.MainMenuV", "class_keskus_1_1_main_menu_v.html", null ],
      [ "Keskus.MainWindow", "class_keskus_1_1_main_window.html", null ],
      [ "Keskus.MonthCalendarV", "class_keskus_1_1_month_calendar_v.html", null ],
      [ "Keskus.NewBooking", "class_keskus_1_1_new_booking.html", null ],
      [ "Keskus.NewBookingV", "class_keskus_1_1_new_booking_v.html", null ],
      [ "Keskus.Reports", "class_keskus_1_1_reports.html", null ],
      [ "Keskus.ReportV", "class_keskus_1_1_report_v.html", null ],
      [ "Keskus.ReportV", "class_keskus_1_1_report_v.html", null ],
      [ "Keskus.RoomDetailsV", "class_keskus_1_1_room_details_v.html", null ],
      [ "Keskus.RoomsV", "class_keskus_1_1_rooms_v.html", null ],
      [ "Keskus.RoomsV", "class_keskus_1_1_rooms_v.html", null ],
      [ "Keskus.RoomsV", "class_keskus_1_1_rooms_v.html", null ],
      [ "Keskus.RoomUpdateV", "class_keskus_1_1_room_update_v.html", null ],
      [ "Keskus.RoomUpdateV", "class_keskus_1_1_room_update_v.html", null ],
      [ "Keskus.RuumV", "class_keskus_1_1_ruum_v.html", null ],
      [ "Keskus.UnconfBookingsV", "class_keskus_1_1_unconf_bookings_v.html", null ]
    ] ],
    [ "IStyleConnector", null, [
      [ "Keskus.BookingsConfirmedV", "class_keskus_1_1_bookings_confirmed_v.html", null ],
      [ "Keskus.BookingsConfirmedV", "class_keskus_1_1_bookings_confirmed_v.html", null ],
      [ "Keskus.BookingsUnconfirmedV", "class_keskus_1_1_bookings_unconfirmed_v.html", null ],
      [ "Keskus.BookingsUnconfirmedV", "class_keskus_1_1_bookings_unconfirmed_v.html", null ]
    ] ],
    [ "Keskus.BLL.Logger", "class_keskus_1_1_b_l_l_1_1_logger.html", null ],
    [ "Page", null, [
      [ "Keskus.AddCustomerV", "class_keskus_1_1_add_customer_v.html", null ],
      [ "Keskus.BookingDetails", "class_keskus_1_1_booking_details.html", null ],
      [ "Keskus.BookingDetailsV", "class_keskus_1_1_booking_details_v.html", null ],
      [ "Keskus.BookingsConfirmedV", "class_keskus_1_1_bookings_confirmed_v.html", null ],
      [ "Keskus.BookingsConfirmedV", "class_keskus_1_1_bookings_confirmed_v.html", null ],
      [ "Keskus.BookingsConfirmedV", "class_keskus_1_1_bookings_confirmed_v.html", null ],
      [ "Keskus.BookingsUnconfirmedV", "class_keskus_1_1_bookings_unconfirmed_v.html", null ],
      [ "Keskus.BookingsUnconfirmedV", "class_keskus_1_1_bookings_unconfirmed_v.html", null ],
      [ "Keskus.BookingsUnconfirmedV", "class_keskus_1_1_bookings_unconfirmed_v.html", null ],
      [ "Keskus.BookingUpdateV", "class_keskus_1_1_booking_update_v.html", null ],
      [ "Keskus.BookingUpdateV", "class_keskus_1_1_booking_update_v.html", null ],
      [ "Keskus.BookingUpdateV", "class_keskus_1_1_booking_update_v.html", null ],
      [ "Keskus.CalendarV", "class_keskus_1_1_calendar_v.html", null ],
      [ "Keskus.CalenderV", "class_keskus_1_1_calender_v.html", null ],
      [ "Keskus.ConfBookingsV", "class_keskus_1_1_conf_bookings_v.html", null ],
      [ "Keskus.CustomerAddV", "class_keskus_1_1_customer_add_v.html", null ],
      [ "Keskus.CustomerAddV", "class_keskus_1_1_customer_add_v.html", null ],
      [ "Keskus.CustomerAddV", "class_keskus_1_1_customer_add_v.html", null ],
      [ "Keskus.CustomersV", "class_keskus_1_1_customers_v.html", null ],
      [ "Keskus.CustomersV", "class_keskus_1_1_customers_v.html", null ],
      [ "Keskus.CustomersV", "class_keskus_1_1_customers_v.html", null ],
      [ "Keskus.CustomerUpdateV", "class_keskus_1_1_customer_update_v.html", null ],
      [ "Keskus.CustomerUpdateV", "class_keskus_1_1_customer_update_v.html", null ],
      [ "Keskus.CustomerUpdateV", "class_keskus_1_1_customer_update_v.html", null ],
      [ "Keskus.MonthCalendarV", "class_keskus_1_1_month_calendar_v.html", null ],
      [ "Keskus.NewBooking", "class_keskus_1_1_new_booking.html", null ],
      [ "Keskus.NewBookingV", "class_keskus_1_1_new_booking_v.html", null ],
      [ "Keskus.Reports", "class_keskus_1_1_reports.html", null ],
      [ "Keskus.ReportV", "class_keskus_1_1_report_v.html", null ],
      [ "Keskus.ReportV", "class_keskus_1_1_report_v.html", null ],
      [ "Keskus.ReportV", "class_keskus_1_1_report_v.html", null ],
      [ "Keskus.RoomDetailsV", "class_keskus_1_1_room_details_v.html", null ],
      [ "Keskus.RoomsV", "class_keskus_1_1_rooms_v.html", null ],
      [ "Keskus.RoomsV", "class_keskus_1_1_rooms_v.html", null ],
      [ "Keskus.RoomsV", "class_keskus_1_1_rooms_v.html", null ],
      [ "Keskus.RoomsV", "class_keskus_1_1_rooms_v.html", null ],
      [ "Keskus.RoomUpdateV", "class_keskus_1_1_room_update_v.html", null ],
      [ "Keskus.RoomUpdateV", "class_keskus_1_1_room_update_v.html", null ],
      [ "Keskus.RoomUpdateV", "class_keskus_1_1_room_update_v.html", null ],
      [ "Keskus.UnconfBookingsV", "class_keskus_1_1_unconf_bookings_v.html", null ]
    ] ],
    [ "TestRakendus.Program", "class_test_rakendus_1_1_program.html", null ],
    [ "Keskus.BLL.Report.ReportBO", "class_keskus_1_1_b_l_l_1_1_report_1_1_report_b_o.html", [
      [ "Keskus.BLL.Report.CustomerReportBO", "class_keskus_1_1_b_l_l_1_1_report_1_1_customer_report_b_o.html", null ],
      [ "Keskus.BLL.Report.RoomReportBO", "class_keskus_1_1_b_l_l_1_1_report_1_1_room_report_b_o.html", null ]
    ] ],
    [ "Keskus.BLL.Report.ReportService", "class_keskus_1_1_b_l_l_1_1_report_1_1_report_service.html", null ],
    [ "Keskus.DAL.Room", "class_keskus_1_1_d_a_l_1_1_room.html", null ],
    [ "Keskus.BLL.Room.RoomBO", "class_keskus_1_1_b_l_l_1_1_room_1_1_room_b_o.html", null ],
    [ "Keskus.BLL.Room.RoomService", "class_keskus_1_1_b_l_l_1_1_room_1_1_room_service.html", null ],
    [ "Keskus.ViewHelpers.ViewHelper", "class_keskus_1_1_view_helpers_1_1_view_helper.html", null ],
    [ "Window", null, [
      [ "Keskus.LoginV", "class_keskus_1_1_login_v.html", null ],
      [ "Keskus.LoginV", "class_keskus_1_1_login_v.html", null ],
      [ "Keskus.LoginV", "class_keskus_1_1_login_v.html", null ],
      [ "Keskus.MainMenuV", "class_keskus_1_1_main_menu_v.html", null ],
      [ "Keskus.MainMenuV", "class_keskus_1_1_main_menu_v.html", null ],
      [ "Keskus.MainMenuV", "class_keskus_1_1_main_menu_v.html", null ],
      [ "Keskus.MainWindow", "class_keskus_1_1_main_window.html", null ],
      [ "Keskus.RuumV", "class_keskus_1_1_ruum_v.html", null ]
    ] ]
];