//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keskus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingID { get; set; }
        public System.DateTime Date { get; set; }
        public int RoomID { get; set; }
        public int CustomerID { get; set; }
        public int Participants { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Confirmed { get; set; }
        public int AdminID { get; set; }
        public string AdditionalInfo { get; set; }
        public Nullable<System.DateTime> Archived { get; set; }
    
        public virtual Administrator Administrator { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Room Room { get; set; }
    }
}
