//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keskus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ContactID { get; set; }
        public int CustomerID { get; set; }
        public int ContactTypeID { get; set; }
        public string Value { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ContactType ContactType { get; set; }
    }
}
